apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamvault.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "streamvault.componentSelectorLabels" (list . "postgres") | nindent 4 }}
