{{- $existing := lookup "v1" "Secret" .Release.Namespace (include "streamvault.secretName" .) -}}
{{- $existingData := ($existing.data | default dict) -}}

{{- $pgPass := "" -}}
{{- if hasKey $existingData "postgres-password" -}}
  {{- $pgPass = index $existingData "postgres-password" | b64dec -}}
{{- else -}}
  {{- $pgPass = .Values.sv.postgres.password | default (randAlphaNum 32) -}}
{{- end -}}

{{- $redisPass := "" -}}
{{- if hasKey $existingData "redis-password" -}}
  {{- $redisPass = index $existingData "redis-password" | b64dec -}}
{{- else -}}
  {{- $redisPass = .Values.sv.redis.password | default (randAlphaNum 32) -}}
{{- end -}}

{{- $secretKey := "" -}}
{{- if hasKey $existingData "secret-key" -}}
  {{- $secretKey = index $existingData "secret-key" | b64dec -}}
{{- else -}}
  {{- $secretKey = .Values.sv.secretKey | default (randAlphaNum 48) -}}
{{- end -}}

{{- $grafanaPass := "" -}}
{{- if .Values.sv.observability.enabled -}}
  {{- if hasKey $existingData "grafana-admin-password" -}}
    {{- $grafanaPass = index $existingData "grafana-admin-password" | b64dec -}}
  {{- else -}}
    {{- $grafanaPass = .Values.sv.observability.grafana.adminPassword | default (randAlphaNum 32) -}}
  {{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamvault.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamvault.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ $pgPass | b64enc | quote }}
  redis-password: {{ $redisPass | b64enc | quote }}
  secret-key: {{ $secretKey | b64enc | quote }}
{{- if and .Values.sv.core.externalS3.enabled .Values.sv.core.externalS3.secretKey }}
  external-s3-secret-key: {{ .Values.sv.core.externalS3.secretKey | b64enc | quote }}
{{- end }}
{{- if .Values.sv.observability.enabled }}
  grafana-admin-password: {{ $grafanaPass | b64enc | quote }}
{{- end }}
