apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamvault.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamvault.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ required "sv.postgres.password is required" .Values.sv.postgres.password | b64enc | quote }}
  redis-password: {{ required "sv.redis.password is required" .Values.sv.redis.password | b64enc | quote }}
  jwt-secret: {{ required "sv.core.jwtSecret is required" .Values.sv.core.jwtSecret | b64enc | quote }}
  kafka-cluster-id: {{ required "sv.kafka.clusterId is required" .Values.sv.kafka.clusterId | b64enc | quote }}
{{- if .Values.sv.observability.enabled }}
  grafana-admin-password: {{ required "sv.observability.grafana.adminPassword is required when observability is enabled" .Values.sv.observability.grafana.adminPassword | b64enc | quote }}
{{- end }}
