global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: streamvault-core
    static_configs:
      - targets: ["streamvault-core:8080"]
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: streamvault-pipeline
    static_configs:
      - targets: ["streamvault-pipeline:8081"]
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: envoy
    static_configs:
      - targets: ["streamvault-envoy:9901"]
    metrics_path: /stats/prometheus
    scrape_interval: 30s
