apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamvault.fullname" . }}-rustfs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: rustfs
spec:
  type: ClusterIP
  selector:
    {{- include "streamvault.componentSelectorLabels" (list . "rustfs") | nindent 4 }}
  ports:
    - name: s3
      port: {{ .Values.sv.rustfs.port }}
      targetPort: s3
      protocol: TCP
    - name: console
      port: {{ .Values.sv.rustfs.consolePort }}
      targetPort: console
      protocol: TCP
