apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamvault.fullname" . }}-envoy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: envoy
spec:
  type: {{ .Values.sv.envoy.service.type }}
  ports:
    - name: http
      port: {{ .Values.sv.envoy.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.sv.envoy.service.httpsPort }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "streamvault.componentSelectorLabels" (list . "envoy") | nindent 4 }}
