apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "streamvault.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "streamvault.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "streamvault.componentSelectorLabels" (list . "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "streamvault.componentSelectorLabels" (list . "redis") | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.sv.redis.image.repository }}:{{ .Values.sv.redis.image.tag }}"
          imagePullPolicy: {{ .Values.sv.redis.image.pullPolicy }}
          command:
            - sh
            - -c
            - redis-server --requirepass $REDIS_PASSWORD
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "streamvault.secretName" . }}
                  key: redis-password
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli --no-auth-warning -a $REDIS_PASSWORD ping
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli --no-auth-warning -a $REDIS_PASSWORD ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.sv.redis.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        {{- if .Values.sv.redis.storageClass }}
        storageClassName: {{ .Values.sv.redis.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.sv.redis.storage }}
