{{- if .Values.sv.observability.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamvault.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.sv.observability.grafana.service.type }}
  ports:
    - name: http
      port: {{ .Values.sv.observability.grafana.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "streamvault.componentSelectorLabels" (list . "grafana") | nindent 4 }}
{{- end }}
