apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streamvault.fullname" . }}-core
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
spec:
  replicas: {{ .Values.sv.core.replicas }}
  selector:
    matchLabels:
      {{- include "streamvault.componentSelectorLabels" (list . "core") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "streamvault.componentSelectorLabels" (list . "core") | nindent 8 }}
    spec:
      containers:
        - name: core
          image: "{{ .Values.sv.core.image.repository }}:{{ .Values.sv.core.image.tag }}"
          imagePullPolicy: {{ .Values.sv.core.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "{{ .Values.sv.postgres.username }}"
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "streamvault.secretName" . }}
                  key: postgres-password
            - name: QUARKUS_DATASOURCE_REACTIVE_URL
              value: "postgresql://{{ include "streamvault.fullname" . }}-postgres:5432/{{ .Values.sv.postgres.database }}"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ include "streamvault.fullname" . }}-kafka:9092"
            - name: STREAMVAULT_AUTH_JWT_PRIVATE_KEY_LOCATION
              value: /jwt/private.pem
            - name: STREAMVAULT_AUTH_JWT_PUBLIC_KEY_LOCATION
              value: /jwt/cert.pem
          volumeMounts:
            - name: jwt-keys
              mountPath: /jwt
              readOnly: true
          livenessProbe:
            httpGet:
              path: {{ .Values.sv.core.healthPath }}
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.sv.core.healthPath }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.sv.core.resources | nindent 12 }}
      volumes:
        - name: jwt-keys
          secret:
            secretName: {{ include "streamvault.secretName" . }}
            items:
              - key: jwt-private-key
                path: private.pem
              - key: jwt-cert
                path: cert.pem
