apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streamvault.fullname" . }}-pipeline
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: pipeline
spec:
  replicas: {{ .Values.sv.pipeline.replicas }}
  selector:
    matchLabels:
      {{- include "streamvault.componentSelectorLabels" (list . "pipeline") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "streamvault.componentSelectorLabels" (list . "pipeline") | nindent 8 }}
    spec:
      containers:
        - name: pipeline
          image: "{{ .Values.sv.pipeline.image.repository }}:{{ .Values.sv.pipeline.image.tag }}"
          imagePullPolicy: {{ .Values.sv.pipeline.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "streamvault.secretName" . }}
                  key: postgres-password
            - name: DB_URL
              value: "postgresql://{{ .Values.sv.postgres.username }}:$(POSTGRES_PASSWORD)@{{ include "streamvault.fullname" . }}-postgres:5432/{{ .Values.sv.postgres.pipelineDatabase }}"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ include "streamvault.fullname" . }}-kafka:9092"
            - name: STREAMVAULT_S3_ENDPOINT
              value: "http://{{ include "streamvault.fullname" . }}-rustfs:{{ .Values.sv.rustfs.port }}"
            - name: STREAMVAULT_S3_ACCESS_KEY
              value: {{ .Values.sv.rustfs.accessKey | quote }}
            - name: STREAMVAULT_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "streamvault.secretName" . }}
                  key: rustfs-secret-key
            - name: STREAMVAULT_S3_BUCKET
              value: {{ .Values.sv.rustfs.bucket | quote }}
            - name: STREAMVAULT_S3_REGION
              value: {{ .Values.sv.rustfs.region | quote }}
            - name: STREAMVAULT_S3_PATH_STYLE
              value: "true"
          livenessProbe:
            httpGet:
              path: {{ .Values.sv.pipeline.healthPath }}
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.sv.pipeline.healthPath }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.sv.pipeline.resources | nindent 12 }}
