apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamvault.fullname" . }}-pipeline
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: pipeline
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
  selector:
    {{- include "streamvault.componentSelectorLabels" (list . "pipeline") | nindent 4 }}
